### ISSUE TITLE
0 connected

### ISSUE THREAD

**Issue by leif-erickson** [lopter/lightsd#28]
Been using lighted for a while now! Recently switched to google wifi and only 22 of 30 lights found, but 0 connected...

**Comment by lopter** [comment]
Hello @ericksonwinter,

Happy to know lighstsd has been useful to you! Would love to know more about how you are using lightsd.

lightsd doesn't really make a difference between a light that's found and connected, a bulb can't actually be "connected" to lightsd because they communicate over UDP.

So I'm not sure to understand what you mean, but I have a couple questions:

- What does `ps aux | grep lightsd` displays?
- the bulbs and lightsd need to be on the same network (same IPv4 subnet), is that still the case with your WiFi configuration changes?

Best

**Comment by leif-erickson** [comment]
Thanks!

I got interrupted and didn't mean to be so brief, but yes, I have been
using lightsd  to make changes hourly for probably a couple years at least.
I setup a daemon on tcp 8080 and have a ruby script that determines hsbk
for the hour and sends the change to appropriate lights.

This has worked until I changed wifi recently (orbi using 10.0.0/24 to
192.27.86/24).  The lights all show up and are more responsive than ever,
except fort the automation.

It is likely the network, just going you may have recommendations of where
to start looking?

Thanks!  Love the program!
Winter

**Comment by lopter** [comment]
Thanks for the details!

I think an easy way to check if lightsd and your bulbs are on the same network is to connect to the WiFi network of the bulbs using a laptop (for example). Then you can lookup the ip address/subnet of the WiFi interface of the laptop and compare that with the ip address of the RaspberryPi.

**Comment by leif-erickson** [comment]
I ended up switching back to Orbi from Google WiFi...not enough bandwidth,
strangely.

Anyway, you were likely correct...I didn't check before restoring the old
network, but I imagine the subnet was different probably on the rpi, since
my phone controlled the lights just fine.

Thanks for your quick response!  I really should integrate more into my
setup with your daemon.  It appears that LIFX has come very close to
replicating the color/brightness/on-off with newest android app, although
there are so many more things I can do since I already have the code to
connect to your daemon.

Thanks again,
Winter

**Comment by lopter** [comment]
You're welcome, I'm closing this thread but let me know if you have any question! I'm still monitoring the lightsd thread in the LIFX forum ([link](https://community.lifx.com/t/lightsd-a-daemon-with-a-json-rpc-api-to-control-your-bulbs/446)) as well.
