### ISSUE TITLE
Firmware updating/onboarding

### ISSUE THREAD

**Issue by nelix** [lopter/lightsd#7]
The worst thing about lifx is the onboarding process and trying to get firmware updates to work via the mobile app. Its even harder if you have new versions of android and 5ghz mixed networks.
It would be awesome if I just plugged the bulb in and lightsd connected to its SSID, onboarded it onto the network and gave it the latest firmware.

Is that possible?

**Comment by lopter** [comment]
Hello,

It's possible, but not interesting since lightsd deals pretty well with any firmware versions and will emulate some features for older firmwares. In other words lightsd kinda make updating your firmware an useless thing to do, especially if you run your bulbs in a segregated network (security yada, yada…).

Moreover firmware updates are really a small –yet annoying, I understand– part of the bulb use and I'd rather focus on the main features.

The only incentive I see for this is to setup an home-brewed firmware on the bulbs. I don't think anyone has been planning to work on such a thing so far.

Best
